services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5001
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=src:create_app
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
